title: Dok
description: documentation system
introduction: "Dok, a low-tech tool that allows you to document (almost) everything"
navigation:
  "Dok": "index"
  "Content": "content"
  "About": "about"
